# Generated by Django 4.1.2 on 2022-10-29 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgingIndex',
            fields=[
                ('aging_index_id', models.PositiveIntegerField(primary_key='true', serialize=False)),
                ('year', models.IntegerField()),
                ('city', models.CharField(max_length=255)),
                ('men_index', models.DecimalField(decimal_places=2, max_digits=5, max_length=5)),
                ('women_index', models.DecimalField(decimal_places=2, max_digits=5, max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='DesertionRate',
            fields=[
                ('desertion_id', models.PositiveIntegerField(primary_key='true', serialize=False)),
                ('year', models.IntegerField()),
                ('educational_level', models.CharField(choices=[('m-prees', 'Preescolar'), ('m-bapri', 'Basica Primaria'), ('m-basecu', 'Basica Secundaria'), ('m-media', 'Media')], max_length=256)),
                ('desertion_index', models.DecimalField(decimal_places=2, max_digits=5, max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='ExtremeMonetaryPoverty',
            fields=[
                ('extreme_monetary_poverty_id', models.PositiveIntegerField(primary_key='true', serialize=False)),
                ('year', models.IntegerField()),
                ('city', models.CharField(max_length=255)),
                ('poverty_index', models.DecimalField(decimal_places=2, max_digits=5, max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='FamilyViolence',
            fields=[
                ('family_violence_id', models.PositiveIntegerField(primary_key='true', serialize=False)),
                ('year', models.IntegerField()),
                ('family_violence_amount', models.IntegerField()),
                ('older_adult_index', models.IntegerField()),
                ('children_teens_index', models.IntegerField()),
                ('family_members_index', models.IntegerField()),
                ('partner_index', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MonetaryPoverty',
            fields=[
                ('monetary_poverty_id', models.PositiveIntegerField(primary_key='true', serialize=False)),
                ('year', models.IntegerField()),
                ('city', models.CharField(max_length=255)),
                ('poverty_index', models.DecimalField(decimal_places=2, max_digits=5, max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='SchoolEnrollment',
            fields=[
                ('enrollment_id', models.PositiveIntegerField(primary_key='true', serialize=False)),
                ('year', models.IntegerField()),
                ('educational_level', models.CharField(choices=[('m-prees', 'Preescolar'), ('m-bapri', 'Basica Primaria'), ('m-basecu', 'Basica Secundaria'), ('m-media', 'Media')], max_length=256)),
                ('type_enrollment', models.CharField(choices=[('MO', 'Matricula Oficial'), ('MP', 'Matricula Privada')], max_length=256)),
                ('amount_enrollment', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='VehicleRegistration',
            fields=[
                ('vehicule_registration_id', models.PositiveIntegerField(primary_key='true', serialize=False)),
                ('year', models.IntegerField()),
                ('vehicule_type', models.CharField(choices=[('t-auto', 'Automovil'), ('t-moto', 'Motocicleta'), ('t-otro', 'Otros')], max_length=256)),
                ('vehicule_registration_index', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='VehicleViolation',
            fields=[
                ('vehicule_violation_id', models.PositiveIntegerField(primary_key='true', serialize=False)),
                ('year', models.IntegerField()),
                ('vehicule_type', models.CharField(choices=[('t-auto', 'Automovil'), ('t-moto', 'Motocicleta'), ('t-otro', 'Otros')], max_length=256)),
                ('vehicule_violation_index', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ViolentDeaths',
            fields=[
                ('violent_death_id', models.PositiveIntegerField(primary_key='true', serialize=False)),
                ('year', models.IntegerField()),
                ('violent_death_amount', models.IntegerField()),
                ('suicide_index', models.DecimalField(decimal_places=2, max_digits=5, max_length=5)),
                ('accidental_deaths_index', models.DecimalField(decimal_places=2, max_digits=5, max_length=5)),
                ('deaths_transportation_accidents_index', models.DecimalField(decimal_places=2, max_digits=5, max_length=5)),
                ('homicidies_index', models.DecimalField(decimal_places=2, max_digits=5, max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='YouthIndex',
            fields=[
                ('youth_index_id', models.PositiveIntegerField(primary_key='true', serialize=False)),
                ('year', models.IntegerField()),
                ('city', models.CharField(max_length=255)),
                ('men_index', models.DecimalField(decimal_places=2, max_digits=5, max_length=5)),
                ('women_index', models.DecimalField(decimal_places=2, max_digits=5, max_length=5)),
            ],
        ),
    ]
