# Generated by Django 4.1.2 on 2022-11-03 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_metrics', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schoolenrollment',
            name='amount_enrollment',
        ),
        migrations.RemoveField(
            model_name='schoolenrollment',
            name='type_enrollment',
        ),
        migrations.AddField(
            model_name='schoolenrollment',
            name='amount_enrollment_official',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='schoolenrollment',
            name='amount_enrollment_private',
            field=models.IntegerField(default=0),
        ),
    ]
