# Generated by Django 4.1.2 on 2022-11-03 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_metrics', '0002_remove_schoolenrollment_amount_enrollment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolenrollment',
            name='amount_enrollment_official',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='schoolenrollment',
            name='amount_enrollment_private',
            field=models.IntegerField(),
        ),
    ]
