# Generated by Django 4.1.2 on 2022-11-03 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_metrics', '0003_alter_schoolenrollment_amount_enrollment_official_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicleregistration',
            name='vehicule_registration_index',
        ),
        migrations.RemoveField(
            model_name='vehicleregistration',
            name='vehicule_type',
        ),
        migrations.RemoveField(
            model_name='vehicleviolation',
            name='vehicule_type',
        ),
        migrations.RemoveField(
            model_name='vehicleviolation',
            name='vehicule_violation_index',
        ),
        migrations.AddField(
            model_name='vehicleregistration',
            name='auto_index',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vehicleregistration',
            name='moto_index',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vehicleregistration',
            name='others_index',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vehicleviolation',
            name='auto_index',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vehicleviolation',
            name='moto_index',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vehicleviolation',
            name='others_index',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='vehicleregistration',
            name='vehicule_registration_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='vehicleviolation',
            name='vehicule_violation_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
