# Generated by Django 4.1.2 on 2022-11-03 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_metrics', '0004_remove_vehicleregistration_vehicule_registration_index_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicleregistration',
            name='auto_index',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='vehicleregistration',
            name='moto_index',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='vehicleregistration',
            name='others_index',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='vehicleregistration',
            name='vehicule_registration_id',
            field=models.PositiveIntegerField(primary_key='true', serialize=False),
        ),
        migrations.AlterField(
            model_name='vehicleviolation',
            name='auto_index',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='vehicleviolation',
            name='moto_index',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='vehicleviolation',
            name='others_index',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='vehicleviolation',
            name='vehicule_violation_id',
            field=models.PositiveIntegerField(primary_key='true', serialize=False),
        ),
    ]
